### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by vk1996** [PeteBlackerThe3rd/tflite_analyser#2]
import png
## png pip package not found and manually has to install flatbuffer. kindly add requirements.txt

**Comment by PeteBlackerThe3rd** [comment]
Thanks for letting me know about this. I've added this in commit [e2627b4](https://github.com/PeteBlackerThe3rd/tflite_analyser/commit/e2627b4e38e9d85fce4ab9628d3d889a4d4c007e)
